language: node_js
node_js:
  - "iojs"
  - "7"
script:
  - COVERAGE=true BROWSERS=SLChrome,SLInternetExplorer10,SLFirefox,SLInternetExplorer11,SLiOS9 travis_retry npm run test
  - BROWSERS=SLEdge,SLSafari travis_retry npm run test
after_success:
  - npm install -g codeclimate-test-reporter lcov-result-merger
  - lcov-result-merger "packages/**/.tmp/coverage/report-lcov/lcov.info" > coverage.info
  - codeclimate-test-reporter < coverage.info